In [1]:
import findspark
findspark.init()

In [2]:
from pyspark.sql import SparkSession
spark=SparkSession.builder.appName('dfTest').master('local').getOrCreate()

In [3]:
path1='D:\RetailData\Features data set.csv'
file1=spark.read.option('inferSchema','True').option('header','True').csv(path1)

In [4]:
file1.show(5)

+-----+----------+-----------+----------+---------+---------+---------+---------+---------+-----------+------------+---------+
|Store|      Date|Temperature|Fuel_Price|MarkDown1|MarkDown2|MarkDown3|MarkDown4|MarkDown5|        CPI|Unemployment|IsHoliday|
+-----+----------+-----------+----------+---------+---------+---------+---------+---------+-----------+------------+---------+
|    1|05/02/2010|      42.31|     2.572|       NA|       NA|       NA|       NA|       NA|211.0963582|       8.106|    false|
|    1|12/02/2010|      38.51|     2.548|       NA|       NA|       NA|       NA|       NA|211.2421698|       8.106|     true|
|    1|19/02/2010|      39.93|     2.514|       NA|       NA|       NA|       NA|       NA|211.2891429|       8.106|    false|
|    1|26/02/2010|      46.63|     2.561|       NA|       NA|       NA|       NA|       NA|211.3196429|       8.106|    false|
|    1|05/03/2010|       46.5|     2.625|       NA|       NA|       NA|       NA|       NA|211.3501429|       8.106|    false|
+-----+----------+-----------+----------+---------+---------+---------+---------+---------+-----------+------------+---------+
only showing top 5 rows

In [5]:
file1.printSchema()

root
 |-- Store: integer (nullable = true)
 |-- Date: string (nullable = true)
 |-- Temperature: double (nullable = true)
 |-- Fuel_Price: double (nullable = true)
 |-- MarkDown1: string (nullable = true)
 |-- MarkDown2: string (nullable = true)
 |-- MarkDown3: string (nullable = true)
 |-- MarkDown4: string (nullable = true)
 |-- MarkDown5: string (nullable = true)
 |-- CPI: string (nullable = true)
 |-- Unemployment: string (nullable = true)
 |-- IsHoliday: boolean (nullable = true)

In [6]:
file1.first()

Row(Store=1, Date='05/02/2010', Temperature=42.31, Fuel_Price=2.572, MarkDown1='NA', MarkDown2='NA', MarkDown3='NA', MarkDown4='NA', MarkDown5='NA', CPI='211.0963582', Unemployment='8.106', IsHoliday=False)

In [7]:
file1.take(1)

[Row(Store=1, Date='05/02/2010', Temperature=42.31, Fuel_Price=2.572, MarkDown1='NA', MarkDown2='NA', MarkDown3='NA', MarkDown4='NA', MarkDown5='NA', CPI='211.0963582', Unemployment='8.106', IsHoliday=False)]

In [8]:
from pyspark.sql.functions import col

In [9]:
file1.count()

8190

In [11]:
file1.select(col('Fuel_Price'),col('Store')).show()

+----------+-----+
|Fuel_Price|Store|
+----------+-----+
|     2.572|    1|
|     2.548|    1|
|     2.514|    1|
|     2.561|    1|
|     2.625|    1|
|     2.667|    1|
|      2.72|    1|
|     2.732|    1|
|     2.719|    1|
|      2.77|    1|
|     2.808|    1|
|     2.795|    1|
|      2.78|    1|
|     2.835|    1|
|     2.854|    1|
|     2.826|    1|
|     2.759|    1|
|     2.705|    1|
|     2.668|    1|
|     2.637|    1|
+----------+-----+
only showing top 20 rows

In [12]:
from pyspark.sql.functions import max

In [14]:
file1.select(max('Fuel_Price')).show()

+---------------+
|max(Fuel_Price)|
+---------------+
|          4.468|
+---------------+

In [15]:
file1.select(col('Fuel_Price').alias('petrolPrice')).show()

+-----------+
|petrolPrice|
+-----------+
|      2.572|
|      2.548|
|      2.514|
|      2.561|
|      2.625|
|      2.667|
|       2.72|
|      2.732|
|      2.719|
|       2.77|
|      2.808|
|      2.795|
|       2.78|
|      2.835|
|      2.854|
|      2.826|
|      2.759|
|      2.705|
|      2.668|
|      2.637|
+-----------+
only showing top 20 rows

In [19]:
file1.filter("Fuel_price>'2.72' and Temperature <'41.5' ").show()

+-----+----------+-----------+----------+---------+---------+---------+---------+---------+-----------+------------+---------+
|Store|      Date|Temperature|Fuel_Price|MarkDown1|MarkDown2|MarkDown3|MarkDown4|MarkDown5|        CPI|Unemployment|IsHoliday|
+-----+----------+-----------+----------+---------+---------+---------+---------+---------+-----------+------------+---------+
|    1|14/01/2011|       35.4|     2.983|       NA|       NA|       NA|       NA|       NA|211.4574109|       7.742|    false|
|    1|11/02/2011|      36.39|     3.022|       NA|       NA|       NA|       NA|       NA|212.9367046|       7.742|     true|
|    2|14/01/2011|      33.02|     2.983|       NA|       NA|       NA|       NA|       NA|211.1176713|       8.028|    false|
|    2|21/01/2011|       41.4|     3.016|       NA|       NA|       NA|       NA|       NA|211.4864691|       8.028|    false|
|    2|04/02/2011|      38.25|     2.989|       NA|       NA|       NA|       NA|       NA|212.2240646|       8.028|    false|
|    2|11/02/2011|      33.19|     3.022|       NA|       NA|       NA|       NA|       NA|212.5928624|       8.028|     true|
|    2|04/01/2013|      39.12|     3.161|  2045.13| 34381.53|    26.36|   159.76|  3863.31|223.7137989|       6.237|    false|
|    2|18/01/2013|      40.98|     3.237|  3737.16|   3047.9|     9.26|    49.14|   2758.1|  223.86882|       6.237|    false|
|    4|26/03/2010|      39.91|     2.752|       NA|       NA|       NA|       NA|       NA|126.6050645|       8.623|    false|
|    4|31/12/2010|      38.09|     2.955|       NA|       NA|       NA|       NA|       NA|127.0876774|       7.127|     true|
|    4|07/01/2011|      39.34|      2.98|       NA|       NA|       NA|       NA|       NA|127.1917742|        6.51|    false|
|    4|14/01/2011|       31.6|     2.992|       NA|       NA|       NA|       NA|       NA|127.3009355|        6.51|    false|
|    4|21/01/2011|      38.34|     3.017|       NA|       NA|       NA|       NA|       NA|127.4404839|        6.51|    false|
|    4|28/01/2011|       40.6|     3.022|       NA|       NA|       NA|       NA|       NA|127.5800323|        6.51|    false|
|    4|04/02/2011|      34.61|     2.996|       NA|       NA|       NA|       NA|       NA|127.7195806|        6.51|    false|
|    4|11/02/2011|      33.29|     3.033|       NA|       NA|       NA|       NA|       NA| 127.859129|        6.51|     true|
|    4|02/12/2011|      38.71|     3.176|  9762.39|   160.94|  2260.29|  4767.86|  28604.2|129.8459667|       5.143|    false|
|    4|09/12/2011|      31.64|     3.153|  5857.72|       30|   984.98|   4692.5| 13503.99|129.8555333|       5.143|    false|
|    4|16/12/2011|      36.44|     3.149|  2756.67|     72.3|  1790.15|   777.65| 10261.95|129.8980645|       5.143|    false|
|    4|23/12/2011|      35.92|     3.103|  2461.94|    69.05|  2938.24|       52|  4396.76|129.9845484|       5.143|    false|
+-----+----------+-----------+----------+---------+---------+---------+---------+---------+-----------+------------+---------+
only showing top 20 rows

In [22]:
file1.withColumnRenamed('Fuel_price','Petrol_price').show(3)

+-----+----------+-----------+------------+---------+---------+---------+---------+---------+-----------+------------+---------+
|Store|      Date|Temperature|Petrol_price|MarkDown1|MarkDown2|MarkDown3|MarkDown4|MarkDown5|        CPI|Unemployment|IsHoliday|
+-----+----------+-----------+------------+---------+---------+---------+---------+---------+-----------+------------+---------+
|    1|05/02/2010|      42.31|       2.572|       NA|       NA|       NA|       NA|       NA|211.0963582|       8.106|    false|
|    1|12/02/2010|      38.51|       2.548|       NA|       NA|       NA|       NA|       NA|211.2421698|       8.106|     true|
|    1|19/02/2010|      39.93|       2.514|       NA|       NA|       NA|       NA|       NA|211.2891429|       8.106|    false|
+-----+----------+-----------+------------+---------+---------+---------+---------+---------+-----------+------------+---------+
only showing top 3 rows

In [25]:
file1.where('Temperature<39.93').show()

+-----+----------+-----------+----------+---------+---------+---------+---------+---------+-----------+------------+---------+
|Store|      Date|Temperature|Fuel_Price|MarkDown1|MarkDown2|MarkDown3|MarkDown4|MarkDown5|        CPI|Unemployment|IsHoliday|
+-----+----------+-----------+----------+---------+---------+---------+---------+---------+-----------+------------+---------+
|    1|12/02/2010|      38.51|     2.548|       NA|       NA|       NA|       NA|       NA|211.2421698|       8.106|     true|
|    1|14/01/2011|       35.4|     2.983|       NA|       NA|       NA|       NA|       NA|211.4574109|       7.742|    false|
|    1|11/02/2011|      36.39|     3.022|       NA|       NA|       NA|       NA|       NA|212.9367046|       7.742|     true|
|    2|12/02/2010|      38.49|     2.548|       NA|       NA|       NA|       NA|       NA|210.8979935|       8.324|     true|
|    2|19/02/2010|      39.69|     2.514|       NA|       NA|       NA|       NA|       NA|210.9451605|       8.324|    false|
|    2|14/01/2011|      33.02|     2.983|       NA|       NA|       NA|       NA|       NA|211.1176713|       8.028|    false|
|    2|04/02/2011|      38.25|     2.989|       NA|       NA|       NA|       NA|       NA|212.2240646|       8.028|    false|
|    2|11/02/2011|      33.19|     3.022|       NA|       NA|       NA|       NA|       NA|212.5928624|       8.028|     true|
|    2|04/01/2013|      39.12|     3.161|  2045.13| 34381.53|    26.36|   159.76|  3863.31|223.7137989|       6.237|    false|
|    4|12/02/2010|      28.84|     2.573|       NA|       NA|       NA|       NA|       NA|126.4962581|       8.623|     true|
|    4|19/02/2010|      36.45|      2.54|       NA|       NA|       NA|       NA|       NA|126.5262857|       8.623|    false|
|    4|26/03/2010|      39.91|     2.752|       NA|       NA|       NA|       NA|       NA|126.6050645|       8.623|    false|
|    4|31/12/2010|      38.09|     2.955|       NA|       NA|       NA|       NA|       NA|127.0876774|       7.127|     true|
|    4|07/01/2011|      39.34|      2.98|       NA|       NA|       NA|       NA|       NA|127.1917742|        6.51|    false|
|    4|14/01/2011|       31.6|     2.992|       NA|       NA|       NA|       NA|       NA|127.3009355|        6.51|    false|
|    4|21/01/2011|      38.34|     3.017|       NA|       NA|       NA|       NA|       NA|127.4404839|        6.51|    false|
|    4|04/02/2011|      34.61|     2.996|       NA|       NA|       NA|       NA|       NA|127.7195806|        6.51|    false|
|    4|11/02/2011|      33.29|     3.033|       NA|       NA|       NA|       NA|       NA| 127.859129|        6.51|     true|
|    4|02/12/2011|      38.71|     3.176|  9762.39|   160.94|  2260.29|  4767.86|  28604.2|129.8459667|       5.143|    false|
|    4|09/12/2011|      31.64|     3.153|  5857.72|       30|   984.98|   4692.5| 13503.99|129.8555333|       5.143|    false|
+-----+----------+-----------+----------+---------+---------+---------+---------+---------+-----------+------------+---------+
only showing top 20 rows

In [28]:
mapping= {
        '39.12': 'x',
        '38.71': 'y'
    }
df2 = file1.replace(to_replace=mapping, subset=['Temperature'])
df2.show(100)

+-----+----------+-----------+----------+---------+---------+---------+---------+---------+-----------+------------+---------+
|Store|      Date|Temperature|Fuel_Price|MarkDown1|MarkDown2|MarkDown3|MarkDown4|MarkDown5|        CPI|Unemployment|IsHoliday|
+-----+----------+-----------+----------+---------+---------+---------+---------+---------+-----------+------------+---------+
|    1|05/02/2010|      42.31|     2.572|       NA|       NA|       NA|       NA|       NA|211.0963582|       8.106|    false|
|    1|12/02/2010|      38.51|     2.548|       NA|       NA|       NA|       NA|       NA|211.2421698|       8.106|     true|
|    1|19/02/2010|      39.93|     2.514|       NA|       NA|       NA|       NA|       NA|211.2891429|       8.106|    false|
|    1|26/02/2010|      46.63|     2.561|       NA|       NA|       NA|       NA|       NA|211.3196429|       8.106|    false|
|    1|05/03/2010|       46.5|     2.625|       NA|       NA|       NA|       NA|       NA|211.3501429|       8.106|    false|
|    1|12/03/2010|      57.79|     2.667|       NA|       NA|       NA|       NA|       NA|211.3806429|       8.106|    false|
|    1|19/03/2010|      54.58|      2.72|       NA|       NA|       NA|       NA|       NA| 211.215635|       8.106|    false|
|    1|26/03/2010|      51.45|     2.732|       NA|       NA|       NA|       NA|       NA|211.0180424|       8.106|    false|
|    1|02/04/2010|      62.27|     2.719|       NA|       NA|       NA|       NA|       NA|210.8204499|       7.808|    false|
|    1|09/04/2010|      65.86|      2.77|       NA|       NA|       NA|       NA|       NA|210.6228574|       7.808|    false|
|    1|16/04/2010|      66.32|     2.808|       NA|       NA|       NA|       NA|       NA|   210.4887|       7.808|    false|
|    1|23/04/2010|      64.84|     2.795|       NA|       NA|       NA|       NA|       NA|210.4391228|       7.808|    false|
|    1|30/04/2010|      67.41|      2.78|       NA|       NA|       NA|       NA|       NA|210.3895456|       7.808|    false|
|    1|07/05/2010|      72.55|     2.835|       NA|       NA|       NA|       NA|       NA|210.3399684|       7.808|    false|
|    1|14/05/2010|      74.78|     2.854|       NA|       NA|       NA|       NA|       NA|210.3374261|       7.808|    false|
|    1|21/05/2010|      76.44|     2.826|       NA|       NA|       NA|       NA|       NA|210.6170934|       7.808|    false|
|    1|28/05/2010|      80.44|     2.759|       NA|       NA|       NA|       NA|       NA|210.8967606|       7.808|    false|
|    1|04/06/2010|      80.69|     2.705|       NA|       NA|       NA|       NA|       NA|211.1764278|       7.808|    false|
|    1|11/06/2010|      80.43|     2.668|       NA|       NA|       NA|       NA|       NA|211.4560951|       7.808|    false|
|    1|18/06/2010|      84.11|     2.637|       NA|       NA|       NA|       NA|       NA|211.4537719|       7.808|    false|
|    1|25/06/2010|      84.34|     2.653|       NA|       NA|       NA|       NA|       NA|211.3386526|       7.808|    false|
|    1|02/07/2010|      80.91|     2.669|       NA|       NA|       NA|       NA|       NA|211.2235333|       7.787|    false|
|    1|09/07/2010|      80.48|     2.642|       NA|       NA|       NA|       NA|       NA| 211.108414|       7.787|    false|
|    1|16/07/2010|      83.15|     2.623|       NA|       NA|       NA|       NA|       NA|211.1003854|       7.787|    false|
|    1|23/07/2010|      83.36|     2.608|       NA|       NA|       NA|       NA|       NA|211.2351443|       7.787|    false|
|    1|30/07/2010|      81.84|      2.64|       NA|       NA|       NA|       NA|       NA|211.3699032|       7.787|    false|
|    1|06/08/2010|      87.16|     2.627|       NA|       NA|       NA|       NA|       NA|211.5046621|       7.787|    false|
|    1|13/08/2010|       87.0|     2.692|       NA|       NA|       NA|       NA|       NA|211.6394211|       7.787|    false|
|    1|20/08/2010|      86.65|     2.664|       NA|       NA|       NA|       NA|       NA|211.6033633|       7.787|    false|
|    1|27/08/2010|      85.22|     2.619|       NA|       NA|       NA|       NA|       NA|211.5673056|       7.787|    false|
|    1|03/09/2010|      81.21|     2.577|       NA|       NA|       NA|       NA|       NA|211.5312479|       7.787|    false|
|    1|10/09/2010|      78.69|     2.565|       NA|       NA|       NA|       NA|       NA|211.4951902|       7.787|     true|
|    1|17/09/2010|      82.11|     2.582|       NA|       NA|       NA|       NA|       NA|211.5224596|       7.787|    false|
|    1|24/09/2010|      80.94|     2.624|       NA|       NA|       NA|       NA|       NA|211.5972246|       7.787|    false|
|    1|01/10/2010|      71.89|     2.603|       NA|       NA|       NA|       NA|       NA|211.6719895|       7.838|    false|
|    1|08/10/2010|      63.93|     2.633|       NA|       NA|       NA|       NA|       NA|211.7467544|       7.838|    false|
|    1|15/10/2010|      67.18|      2.72|       NA|       NA|       NA|       NA|       NA|211.8137436|       7.838|    false|
|    1|22/10/2010|      69.86|     2.725|       NA|       NA|       NA|       NA|       NA|211.8612937|       7.838|    false|
|    1|29/10/2010|      69.64|     2.716|       NA|       NA|       NA|       NA|       NA|211.9088438|       7.838|    false|
|    1|05/11/2010|      58.74|     2.689|       NA|       NA|       NA|       NA|       NA|211.9563939|       7.838|    false|
|    1|12/11/2010|      59.61|     2.728|       NA|       NA|       NA|       NA|       NA| 212.003944|       7.838|    false|
|    1|19/11/2010|      51.41|     2.771|       NA|       NA|       NA|       NA|       NA|211.8896737|       7.838|    false|
|    1|26/11/2010|      64.52|     2.735|       NA|       NA|       NA|       NA|       NA|211.7484333|       7.838|     true|
|    1|03/12/2010|      49.27|     2.708|       NA|       NA|       NA|       NA|       NA| 211.607193|       7.838|    false|
|    1|10/12/2010|      46.33|     2.843|       NA|       NA|       NA|       NA|       NA|211.4659526|       7.838|    false|
|    1|17/12/2010|      49.84|     2.869|       NA|       NA|       NA|       NA|       NA|211.4053124|       7.838|    false|
|    1|24/12/2010|      52.33|     2.886|       NA|       NA|       NA|       NA|       NA|211.4051222|       7.838|    false|
|    1|31/12/2010|      48.43|     2.943|       NA|       NA|       NA|       NA|       NA|211.4049321|       7.838|     true|
|    1|07/01/2011|      48.27|     2.976|       NA|       NA|       NA|       NA|       NA|211.4047419|       7.742|    false|
|    1|14/01/2011|       35.4|     2.983|       NA|       NA|       NA|       NA|       NA|211.4574109|       7.742|    false|
|    1|21/01/2011|      44.04|     3.016|       NA|       NA|       NA|       NA|       NA|211.8272343|       7.742|    false|
|    1|28/01/2011|      43.83|      3.01|       NA|       NA|       NA|       NA|       NA|212.1970577|       7.742|    false|
|    1|04/02/2011|      42.27|     2.989|       NA|       NA|       NA|       NA|       NA|212.5668812|       7.742|    false|
|    1|11/02/2011|      36.39|     3.022|       NA|       NA|       NA|       NA|       NA|212.9367046|       7.742|     true|
|    1|18/02/2011|      57.36|     3.045|       NA|       NA|       NA|       NA|       NA|213.2478853|       7.742|    false|
|    1|25/02/2011|       62.9|     3.065|       NA|       NA|       NA|       NA|       NA| 213.535609|       7.742|    false|
|    1|04/03/2011|      59.58|     3.288|       NA|       NA|       NA|       NA|       NA|213.8233327|       7.742|    false|
|    1|11/03/2011|      53.56|     3.459|       NA|       NA|       NA|       NA|       NA|214.1110564|       7.742|    false|
|    1|18/03/2011|      62.76|     3.488|       NA|       NA|       NA|       NA|       NA|214.3627114|       7.742|    false|
|    1|25/03/2011|      69.97|     3.473|       NA|       NA|       NA|       NA|       NA|214.5999389|       7.742|    false|
|    1|01/04/2011|      59.17|     3.524|       NA|       NA|       NA|       NA|       NA|214.8371664|       7.682|    false|
|    1|08/04/2011|      67.84|     3.622|       NA|       NA|       NA|       NA|       NA|215.0743939|       7.682|    false|
|    1|15/04/2011|      71.27|     3.743|       NA|       NA|       NA|       NA|       NA|215.2918561|       7.682|    false|
|    1|22/04/2011|      72.99|     3.807|       NA|       NA|       NA|       NA|       NA|215.4599053|       7.682|    false|
|    1|29/04/2011|      72.03|      3.81|       NA|       NA|       NA|       NA|       NA|215.6279544|       7.682|    false|
|    1|06/05/2011|      64.61|     3.906|       NA|       NA|       NA|       NA|       NA|215.7960035|       7.682|    false|
|    1|13/05/2011|      75.64|     3.899|       NA|       NA|       NA|       NA|       NA|215.9640526|       7.682|    false|
|    1|20/05/2011|      67.63|     3.907|       NA|       NA|       NA|       NA|       NA|215.7339202|       7.682|    false|
|    1|27/05/2011|      77.72|     3.786|       NA|       NA|       NA|       NA|       NA|215.5037878|       7.682|    false|
|    1|03/06/2011|       83.0|     3.699|       NA|       NA|       NA|       NA|       NA|215.2736553|       7.682|    false|
|    1|10/06/2011|      83.13|     3.648|       NA|       NA|       NA|       NA|       NA|215.0435229|       7.682|    false|
|    1|17/06/2011|      86.41|     3.637|       NA|       NA|       NA|       NA|       NA|214.9980596|       7.682|    false|
|    1|24/06/2011|      83.58|     3.594|       NA|       NA|       NA|       NA|       NA|215.0910982|       7.682|    false|
|    1|01/07/2011|      85.55|     3.524|       NA|       NA|       NA|       NA|       NA|215.1841368|       7.962|    false|
|    1|08/07/2011|      85.83|      3.48|       NA|       NA|       NA|       NA|       NA|215.2771754|       7.962|    false|
|    1|15/07/2011|      88.54|     3.575|       NA|       NA|       NA|       NA|       NA|215.3611087|       7.962|    false|
|    1|22/07/2011|      85.77|     3.651|       NA|       NA|       NA|       NA|       NA|215.4222784|       7.962|    false|
|    1|29/07/2011|      86.83|     3.682|       NA|       NA|       NA|       NA|       NA|215.4834482|       7.962|    false|
|    1|05/08/2011|      91.65|     3.684|       NA|       NA|       NA|       NA|       NA| 215.544618|       7.962|    false|
|    1|12/08/2011|      90.76|     3.638|       NA|       NA|       NA|       NA|       NA|215.6057878|       7.962|    false|
|    1|19/08/2011|      89.94|     3.554|       NA|       NA|       NA|       NA|       NA|215.6693107|       7.962|    false|
|    1|26/08/2011|      87.96|     3.523|       NA|       NA|       NA|       NA|       NA|215.7332258|       7.962|    false|
|    1|02/09/2011|      87.83|     3.533|       NA|       NA|       NA|       NA|       NA|215.7971409|       7.962|    false|
|    1|09/09/2011|       76.0|     3.546|       NA|       NA|       NA|       NA|       NA| 215.861056|       7.962|     true|
|    1|16/09/2011|      79.94|     3.526|       NA|       NA|       NA|       NA|       NA|216.0410526|       7.962|    false|
|    1|23/09/2011|       75.8|     3.467|       NA|       NA|       NA|       NA|       NA|216.3758246|       7.962|    false|
|    1|30/09/2011|      79.69|     3.355|       NA|       NA|       NA|       NA|       NA|216.7105965|       7.962|    false|
|    1|07/10/2011|      69.31|     3.285|       NA|       NA|       NA|       NA|       NA|217.0453684|       7.866|    false|
|    1|14/10/2011|      71.74|     3.274|       NA|       NA|       NA|       NA|       NA|217.3552733|       7.866|    false|
|    1|21/10/2011|      63.71|     3.353|       NA|       NA|       NA|       NA|       NA|217.5159762|       7.866|    false|
|    1|28/10/2011|      66.57|     3.372|       NA|       NA|       NA|       NA|       NA|217.6766791|       7.866|    false|
|    1|04/11/2011|      54.98|     3.332|       NA|       NA|       NA|       NA|       NA| 217.837382|       7.866|    false|
|    1|11/11/2011|      59.11|     3.297|  10382.9|  6115.67|   215.07|  2406.62|  6551.42|217.9980849|       7.866|    false|
|    1|18/11/2011|      62.25|     3.308|  6074.12|   254.39|    51.98|   427.39|  5988.57|218.2205088|       7.866|    false|
|    1|25/11/2011|      60.14|     3.236|   410.31|       98| 55805.51|        8|   554.92|218.4676211|       7.866|     true|
|    1|02/12/2011|      48.91|     3.172|  5629.51|       68|  1398.11|  2084.64| 20475.32|218.7147333|       7.866|    false|
|    1|09/12/2011|      43.93|     3.158|  4640.65|       19|   105.02|  3639.42| 14461.82|218.9618456|       7.866|    false|
|    1|16/12/2011|      51.63|     3.159|  5011.32|       67|   347.37|   225.79|  4011.37|219.1794533|       7.866|    false|
|    1|23/12/2011|      47.96|     3.112|  2725.36|    40.48|    634.7|     24.9|  2739.43|219.3577216|       7.866|    false|
|    1|30/12/2011|      44.55|     3.129|   5762.1| 46011.38|   260.36|   983.65|  4735.78|219.5359898|       7.866|     true|
+-----+----------+-----------+----------+---------+---------+---------+---------+---------+-----------+------------+---------+
only showing top 100 rows

In [30]:
df2.filter("Temperature =='x' ").show()

+-----+----+-----------+----------+---------+---------+---------+---------+---------+---+------------+---------+
|Store|Date|Temperature|Fuel_Price|MarkDown1|MarkDown2|MarkDown3|MarkDown4|MarkDown5|CPI|Unemployment|IsHoliday|
+-----+----+-----------+----------+---------+---------+---------+---------+---------+---+------------+---------+
+-----+----+-----------+----------+---------+---------+---------+---------+---------+---+------------+---------+

In [34]:
df2.filter(df2.IsHoliday.startswith('t')).show()

+-----+----------+-----------+----------+---------+---------+---------+---------+---------+-----------+------------+---------+
|Store|      Date|Temperature|Fuel_Price|MarkDown1|MarkDown2|MarkDown3|MarkDown4|MarkDown5|        CPI|Unemployment|IsHoliday|
+-----+----------+-----------+----------+---------+---------+---------+---------+---------+-----------+------------+---------+
|    1|12/02/2010|      38.51|     2.548|       NA|       NA|       NA|       NA|       NA|211.2421698|       8.106|     true|
|    1|10/09/2010|      78.69|     2.565|       NA|       NA|       NA|       NA|       NA|211.4951902|       7.787|     true|
|    1|26/11/2010|      64.52|     2.735|       NA|       NA|       NA|       NA|       NA|211.7484333|       7.838|     true|
|    1|31/12/2010|      48.43|     2.943|       NA|       NA|       NA|       NA|       NA|211.4049321|       7.838|     true|
|    1|11/02/2011|      36.39|     3.022|       NA|       NA|       NA|       NA|       NA|212.9367046|       7.742|     true|
|    1|09/09/2011|       76.0|     3.546|       NA|       NA|       NA|       NA|       NA| 215.861056|       7.962|     true|
|    1|25/11/2011|      60.14|     3.236|   410.31|       98| 55805.51|        8|   554.92|218.4676211|       7.866|     true|
|    1|30/12/2011|      44.55|     3.129|   5762.1| 46011.38|   260.36|   983.65|  4735.78|219.5359898|       7.866|     true|
|    1|10/02/2012|      48.02|     3.409| 13925.06|  6927.23|   101.64|  8471.88|  6886.04|220.2651783|       7.348|     true|
|    1|07/09/2012|      83.96|      3.73|  5204.68|    35.74|    50.94|  4120.32|  2737.17|222.4390153|       6.908|     true|
|    1|23/11/2012|      56.23|     3.211|   883.59|     4.17| 74910.32|   209.91|   303.32|223.5619474|       6.573|     true|
|    1|28/12/2012|      44.79|     3.108| 12659.55| 37101.13|   174.78|    74.46|  1208.86|223.9604143|       6.573|     true|
|    1|08/02/2013|      56.67|     3.417| 32355.16|    729.8|   280.89| 20426.61|  4671.78|224.2350289|       6.525|     true|
|    2|12/02/2010|      38.49|     2.548|       NA|       NA|       NA|       NA|       NA|210.8979935|       8.324|     true|
|    2|10/09/2010|      79.09|     2.565|       NA|       NA|       NA|       NA|       NA|211.1532104|       8.099|     true|
|    2|26/11/2010|      62.98|     2.735|       NA|       NA|       NA|       NA|       NA|211.4062867|       8.163|     true|
|    2|31/12/2010|       47.3|     2.943|       NA|       NA|       NA|       NA|       NA| 211.064774|       8.163|     true|
|    2|11/02/2011|      33.19|     3.022|       NA|       NA|       NA|       NA|       NA|212.5928624|       8.028|     true|
|    2|09/09/2011|      77.97|     3.546|       NA|       NA|       NA|       NA|       NA|215.5148295|       7.852|     true|
|    2|25/11/2011|      56.36|     3.236|   919.71|       62| 77451.26|       23|  1589.43|218.1130269|       7.441|     true|
+-----+----------+-----------+----------+---------+---------+---------+---------+---------+-----------+------------+---------+
only showing top 20 rows